# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiChery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 11, 2, 44, 58, 520099, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 11, 2, 45, 3, 641343, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
